#
# Table structure for table 'user'
#
CREATE TABLE USER_ACCOUNT (
USERID INT(3) NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(10) NOT NULL,
PASSSWORD VARCHAR(30) NOT NULL,
GROUPNAME VARCHAR(10),
PRIMARY KEY (USERID)
);
#
# Data for table 'user'
#
INSERT INTO USER_ACCOUNT (USERNAME, PASSSWORD, GROUPNAME)
VALUES ('LMEADORS', 'PICKLE', 'EMPLOYEE');
INSERT INTO USER_ACCOUNT (USERNAME, PASSSWORD, GROUPNAME)
VALUES ('JDOE', 'TEST', 'EMPLOYEE');
COMMIT;

CREATE TABLE USER_ACCOUNT (
USERID number(3) primary key,
USERNAME VARCHAR2(10) NOT NULL,
PASSSWORD VARCHAR2(30) NOT NULL,
GROUPNAME VARCHAR2(10)
);
INSERT INTO USER_ACCOUNT 
VALUES (1,'LMEADORS', 'PICKLE', 'EMPLOYEE');
INSERT INTO USER_ACCOUNT 
VALUES (2,'JDOE', 'TEST', 'EMPLOYEE');
COMMIT;